services:
  game:
    build: .
    image: duynguyen03/game:v2
    ports:
      - "1609:1609"
    depends_on:
      - db
    restart: always
    networks:
      - default

  db:
    image: mariadb:10.4.24
    environment:
      MYSQL_ROOT_PASSWORD: 12332145
      MYSQL_DATABASE: game
    ports:
      - "3306:3306"
    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: game-network
